# Day 04 Jupyter Notebook - Class Lecture and Tasks
# Asad Ahmed Jalbani

In [10]:
#List Arguments
t1 = [1, 2]
t2 = t1.append(2) #while appending does not assign value
print(t1)

t3 = t1 + [3]
print(t3)

print(t1 is t2)

t4 = [1,2,3,4]
print(t4 is t3)

t5 = ['hello']
print(t5 is t4)

[1, 2, 2]
[1, 2, 2, 3]
False
False
False


In [19]:
t1 = [2,4]
t2 = t1 #this is referencing the same location of t1
print(t2 is t1)

t1[0] = 100
print("T1 = ", t1)
print(t2 is t1)

True
T1 =  [100, 4]
True


## Tuples
A tuple in python si similar to list.

In [23]:
# Empty tuplbe
my_tuple = ()
print(my_tuple)

# tuple having integers
my_tuple = (1,2,3,4,5)
print(my_tuple)

#tuple + mixed datatypes
my_tuple = (1,'hello',9.9,'b')
print(my_tuple)

print(type(my_tuple))

()
(1, 2, 3, 4, 5)
(1, 'hello', 9.9, 'b')
<class 'tuple'>


In [25]:
#tuple using 
my_tuple = 1,2,3
print(my_tuple)

my_tuple = 1, 'hello', 3.4
print(my_tuple)

(1, 2, 3)
(1, 'hello', 3.4)


In [26]:
#create tuple ith one element
var1 = ("Hello")
print(var1, ' Type:  ', type(var1))

var2 = ("Hello",)
print(var2, ' Type: ',type(var2))

Hello  Type:   <class 'str'>
('Hello',)  Type:  <class 'tuple'>


## Accessing Elements

In [28]:
letters = ('p','r','o','g','r','a','m','i','z')
print(letters[-1]) #print z
print(letters[-4]) #print a

z
a


## Tuple Slicing

In [30]:
print(letters[1:5])

('r', 'o', 'g', 'r')


In [33]:
list = [1,2,3,4,8]
print(list)

tuple = (1,2)
print(tuple)

tuple = (list,6)
print(tuple)

[1, 2, 3, 4, 8]
(1, 2)
([1, 2, 3, 4, 8], 6)


In [36]:
tuple[0][2] = 9
print(tuple[0][2])

9


In [39]:
#There are only 2 methods in tuple index and count

letters = ('p','r','o','g','r','a','m','i','z')
print(letters.index('z'))
print(letters.count('r'))

8
2


In [41]:
#Iterating through a Tuple

letters = ('p','r','o','g','r','a','m','i','z')
for i in letters:
    print(i)

p
r
o
g
r
a
m
i
z


In [43]:
#check if item exist of not

letters = ('p','r','o','g','r','a','m','i','z')
print('C' in letters) #False
print('m' in letters) #True

False
True


In [44]:
#check if item exist in string

string = 'asad'
print("d" in string) # True

True


In [46]:
#Aliasing

a = [1,2,3]
a[1] = 10
b = a
b is a

True

# Dictionaries

## There is no index in dictionary, you need find key value pair here

In [50]:
# creating a dictionary
my_dict = {'key1':'value1', 'key2':'value2', 'key3':'value3'}

# Accessing ditionary value
print(my_dict['key1'])

# Modifying value
my_dict['key2'] = 'updated value'
print(my_dict)

value1
{'key1': 'value1', 'key2': 'updated value', 'key3': 'value3'}


In [56]:
# Creating a dictionary usng dict() constructor
# Adding value in dictionary 
d = dict(name='asad',age=23, city='Islamabad')
print(d)
print('Type: ',type(d))


{'name': 'asad', 'age': 23, 'city': 'Islamabad'}
Type:  <class 'dict'>
{'name': 'asad', 'age': 24, 'city': 'Islamabad'}
{'name': 'asad', 'city': 'Islamabad'}
{'name': 'asad', 'city': 'Islamabad', 'Job Role': 'Data Science Trainee'}


In [57]:
# Updating Value in dictionary
d['age'] = 24
print(d)

{'name': 'asad', 'city': 'Islamabad', 'Job Role': 'Data Science Trainee', 'age': 24}


In [58]:
# Removing a value in dictionary
del d['age']
print(d)


{'name': 'asad', 'city': 'Islamabad', 'Job Role': 'Data Science Trainee'}


In [59]:
# Adding Value in dictionary 

d['Job Role'] = 'Data Science Trainee'
print(d)

{'name': 'asad', 'city': 'Islamabad', 'Job Role': 'Data Science Trainee'}


In [61]:
# Checking length of dictionary
print(len(d)) # 3

#Checking if key exists
print("name" in d) # True

3
True


In [70]:
# keys()
print('Keys: ',d.keys())

# values()
print('Values: ',d.values())

# items()
print('Items: ',d.items())

# get()
print('Value: ',d.get('city'))

Keys:  dict_keys(['name', 'city', 'Job Role'])
Values:  dict_values(['asad', 'Islamabad', 'Data Science Trainee'])
Items:  dict_items([('name', 'asad'), ('city', 'Islamabad'), ('Job Role', 'Data Science Trainee')])
Value:  Islamabad


In [99]:
# Nested Dictionaries 
person = {
    '1': {'name': 'asad1', 'age': '20', 'job':'soft'},
    '2': {'name': 'asad2', 'age': '21', 'job':'soft1'},
    '3': {'name': 'asad3', 'age': '22', 'job':{'a','b','c'}},
    '4': {'name': 'asad4', 'age': '23', 'job':'soft3'},
    '5': {'name': 'asad5', 'age': '24', 'job':'soft4'},
}
print(person['3']['job'])

{'b', 'c', 'a'}


In [104]:
# Updating b1 value
person['3']['job'].update('b3')
print(person['3']['job'])

{'c', 'b3', 'a', 'b', '3'}


In [107]:
# appending value at last
person['3']['job'].add('b3')
print(person)

{'1': {'name': 'asad1', 'age': '20', 'job': 'soft'}, '2': {'name': 'asad2', 'age': '21', 'job': 'soft1'}, '3': {'name': 'asad3', 'age': '22', 'job': {'c', 'b3', 'a', 'b', '3'}}, '4': {'name': 'asad4', 'age': '23', 'job': 'soft3'}, '5': {'name': 'asad5', 'age': '24', 'job': 'soft4'}}


# Module in Python

In [109]:
import numpy as np

# create list named list1
list1 = [1,2,3]

# create numpy array from list
array = np.array(list1)

print(array)

[1 2 3]


In [119]:
import numpy as np

# Creating array ith np.zeros()
array1 = np.zeros(3);
print(array1)
print('Type: ',type(array1))

[0. 0. 0.]
Type:  <class 'numpy.ndarray'>


In [123]:
import numpy as np

# Creating array ith np.arrange()
array2 = np.arange(1,9,2)
print(array2)

[1 3 5 7]


In [128]:
import numpy as np

# Creating array using np.random.rand()
arrayR = np.random.rand(2,2,3)
print(arrayR)

[[[0.63619265 0.77105211 0.18256038]
  [0.22021278 0.75341415 0.28529905]]

 [[0.27897082 0.45206746 0.61507006]
  [0.81490475 0.41419329 0.45302611]]]


In [133]:
import numpy as np

# Creating empty numpy array
arrayE = np.empty(4)
print(arrayE)

[0.68976528 0.00127473 0.24709133 0.73906397]


In [139]:
import numpy as np

# Creating 2d array
array2d = np.array([
    [[1,2,3,4],
    [9,8,7,6],
    [4,5,6,7]],
    
    [[1,2,3,4],
    [9,8,7,6],
    [4,5,6,7]]
])
print(array2d)

[[[1 2 3 4]
  [9 8 7 6]
  [4 5 6 7]]

 [[1 2 3 4]
  [9 8 7 6]
  [4 5 6 7]]]


In [145]:
import numpy as np
array = np.zeros((3,9,3,2))
print(array)

[[[[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]]


 [[[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]]


 [[[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]]]


In [161]:
import numpy as np
array = np.arange(1,2)
print(array)

[1]


In [155]:
import numpy as np
array = np.random.rand(3,2,3,4)
print(array)

[[[[0.87580371 0.33371254 0.9181444  0.21134129]
   [0.16347456 0.07026958 0.2358564  0.46607333]
   [0.87211942 0.05059262 0.75331327 0.49061125]]

  [[0.68680874 0.50268695 0.45541406 0.39332773]
   [0.9444337  0.09267646 0.30240115 0.32826351]
   [0.57367597 0.63250906 0.90376509 0.23112611]]]


 [[[0.93880489 0.66459558 0.79019632 0.71926098]
   [0.42386644 0.86327424 0.27439213 0.91507409]
   [0.15975245 0.94118151 0.26539777 0.74040241]]

  [[0.8580389  0.15598785 0.13520922 0.32666543]
   [0.32707733 0.22073613 0.71042286 0.64202029]
   [0.27141036 0.58059051 0.7956956  0.36263209]]]


 [[[0.50351982 0.94215619 0.52355392 0.36481873]
   [0.70198624 0.00885478 0.69428563 0.09031548]
   [0.94940649 0.0519505  0.20863736 0.75224377]]

  [[0.38189014 0.99732134 0.37313413 0.00701763]
   [0.01187678 0.84200294 0.35882585 0.01263609]
   [0.36147824 0.76302189 0.65189927 0.37944979]]]]


In [171]:
import numpy as np

# Creating N-D array ith specified value
arrayND = np.full((2,2,3),5)
print(arrayND)
print("\n\n Type: ", arrayND.dtype)

[[[5 5 5]
  [5 5 5]]

 [[5 5 5]
  [5 5 5]]]


 Type:  int32


## Numpy I/O Functions